
:_invalid:
Invalid %s < %s >
/END/

:_invalid2:
Invalid %s < %s >. %s
/END/

:assert_args_set:
Argument missing or blank
/END/

:assert_bool_tf:
Boolean string required: [true|false]
/END/

:assert_bhyveopts1:
%s < %s > contains an invalid option. Permissible: <AaCDeHhPSuWwxY>.
/END/

:assert_bhyveopts2:
%s < %s > contains a duplicate character.
/END/

:assert_cellname:
Invalid cellname < %s >. Must start/end with alpha-numeric.
May contain '-' or '_', but not consecutively.
/END/

:assert_cpuset:
Invalid cpuset format < %s >. Must be comma separated intergers, a range, or combination. See man 1 cpuset
/END/

:assert_integer:
Invalid input: < %s >. Integer required.
/END/

:assert_int_comparison:
%s %s %s
/END/

:assert_ipv4:
%s < %s > is not CIDR. Use CIDR notation for IPV4 addr, or <none|DHCP|auto>.
/END/

